### ISSUE TITLE
Help: running examples to benchmark the storage of rasdaman

### ISSUE THREAD

**Issue by shaochengcheng** [adbms-benchmark/storage#2]
Dear @misev,

Hope everything goes well. I am opening this issue to request that could you provide some running examples of this repository to test the storage performance of rasdaman server?

I am following your publication 'Towards a general array database benchmark: measuring storage access", which guides me to this repository. The work presented in the paper is very great to illustrate the basic conceptions when benchmarking array databases. However, when trying to reproduce your results by running this repository, I came across many errors due to insufficient instructions. Thus I am writing this issue to discuss some of the error I met and seek for your suggestions. In the following disscussion, I am focusing on rasdaman server and the storage performance only.

1. Initially, I thought the working flow goes like: generate -> load -> benchmark -> drop. Thus I have a very simple command using many default settings: `run.sh -s rasdaman --system-configs config/rasdaman.properties --generate --load --drop`, however, it came with errors and I realized that:
      1. Never use `--generate` option as it is not implemented.
      2. `--drop` option only takes care of the collection, it doesn't drop the newly created data types, which causes errors for the next testing. Thus I have to manually drop them.

2. Multi-Domain Access is not working. When I used command `run.sh -s rasdaman --system-configs config/rasdaman.properties --load --drop`, it went well at first but met with an error when testing Multi-Domain Access, specifically, the query string is generated in the file system.rasdaman.RasdamanQueryGenerator.java line 421:

    1. The cell base type of an MDD is a struct, even though it contains only one attribute, which makes the expression MDD[interval] >= 0 incompatible.
    2. I modified this part as MDD[interval].0 >= 0

3. Cannot test very large data: when testing size of a 100GB array, the rasdaman always fails to insert the array, the error is: failed to send keep alive message to rasserver:Deadline Exceeded.
  
    1. command is  `run.sh -s rasdaman --system-configs config/rasdaman.properties --load --drop -b 100GB -d 1,2,3,4,5,6`
    2. I tried different rasmgr.conf settings with `time out` values of 300(default), 0(infinite), 60000(huge); but the error still there.

It would be very appreciated if you could provide me some running examples (or settings) to successfully benchmark the storage performance of rasdaman.

Thanks
Chengcheng

**Comment by misev** [comment]
Hi Chengcheng,
appologies for the errors, meanwhile we have adapted this code for a few other benchmarks so something in the storage benchmark might have gotten broken.

1.I. It seems to be true: you can manually generate the data files with something like `head -c 1000 /dev/urandom > 1kB_file.bin`
1.II. Normally you would generate/load the data only once, instead of readoing it on every run. But this sounds like a simple fix in the code.
2.I/II. That is strange, probably the correct fix is to use an atomic type instead of composite with only one attribute.
3. I don't recall how the benchmark imports such large data, it should be done via partial updates. Please attach the rasserver log file in /opt/rasdaman/log after running the command.

**Comment by shaochengcheng** [comment]
Hi @misev,

Thanks so much for your quick response.

For question 3. I realized that the benchmark is filling the database by using a 100GB binary file, which eats the whole memory. And also, yes, I saw the partial updates in the code but it seemed to be commented in the running code.

1. Do you know which version of this repository is runnable for the storage benchmark?

I am new to rasdaman and would like to hear your suggestions for the following questions.

2. Will it cause errors, if max_select_size is larger than the memory (the query results is larger than the main memory). More generally, how to output large query results (larger than the memory) for rasdaman? 

3. Does rasdaman have a kind of master/slave architecture to build up a federated network?

Thanks again
Chengcheng

**Comment by misev** [comment]
No problem Chengcheng, I hope it helps.

1. Probably the tag `v0.5.0-storage_benchmark` should be the right one
2. Probably yes, it depends on the rasdaman version (community or enterprise), but in general you need at least as much RAM as the query result for encoding the final result.
3. This is a feature of enterprise rasdaman, not possible in community

If you have more general questions about rasdaman (community version specific) it would be best to ask on the mailing list: http://rasdaman.org/wiki/MailingLists

**Comment by shaochengcheng** [comment]
Thank you so much!
